#!/bin/sh

set -ex

lb config noauto \
    --architecture amd64 \
    --archive-area "main contrib non-free non-free-firmware" \
    --bootappend-live "boot=live components" locales=zh_CN.UTF-8 \
    --debian-installer live \
    --debian-installer-distribution bookworm \
    --debian-installer-gui true \
    --distribution bookworm \
    --iso-application "Buildroot" \
    --iso-publisher "Buildroot Project" \
    --iso-volume "Buildroot Live" \
    --linux-packages "linux-image linux-headers" \
    --mirror-binary https://mirrors.163.com/debian \
    --mirror-binary-security https://mirrors.163.com/debian-security \
    --mirror-bootstrap https://mirrors.163.com/debian \
    --mirror-chroot https://mirrors.163.com/debian \
    --mirror-chroot-security https://mirrors.163.com/debian-security \
    --mirror-debian-installer https://mirrors.163.com/debian \
    --security true \
    --debug \
    "${@}"
