#!/bin/sh

set -ex

lb config noauto \
    --architecture amd64 \
    --archive-area "main contrib non-free non-free-firmware" \
    --bootappend-live "boot=live components locales=zh_CN.UTF-8 keyboard-layouts=us" \
    --debian-installer live \
    --debian-installer-distribution bookworm \
    --debian-installer-gui true \
    --distribution stable \
    --iso-application "Buildroot" \
    --iso-publisher "Buildroot Project" \
    --iso-volume "Buildroot Live" \
    --linux-packages "linux-image linux-headers" \
    --security true \
    --debug \
    --apt-secure false \
    --apt-indices false \
    --apt-recommends false \
    --updates true \
    "${@}"
