name: ci
on:
  pull_request:
  workflow_dispatch:
  push:
  
jobs:
  live-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - uses: rokibhasansagar/slimhub_actions@main
    - run: sudo apt-get update
    - run: sudo apt-get -y install debootstrap tree
    - run: sudo debootstrap --arch=amd64 sid rootfs
    - name: mount
      run: |
        sudo mount -t proc /proc rootfs/proc
        sudo mount --rbind /dev rootfs/dev
        sudo mount --rbind /sys rootfs/sys
    - run: sudo chroot rootfs /bin/apt-get -y install python3 wget git live-build debian-archive-keyring gpg dosfstools genisoimage squashfs-tools xorriso grub-common grub-pc-bin grub-efi-amd64-bin nano
    - run: sudo chroot rootfs /bin/wget https://github.com/dpkg123/lb-config/raw/main/build.py
    - run: sudo chroot rootfs /bin/python3 /build.py
    - run: sudo du -h rootfs/ci/*.iso
    - uses: actions/upload-artifact@v3
      with:
        name: iso
        path: rootfs/ci/live-image-amd64.hybrid.iso
