name: ci
on:
  pull_request:
  workflow_dispatch:
  push:
  
jobs:
  live-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - run: sudo apt update
    - run: docker rmi -f $(docker images -q)
    - run: wget -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q
    - run: sudo apt-get -y install debootstrap
    - run: sudo debootstrap --arch=amd64 --variant=minbase bookworm rootfs
    - name: mount
      run: |
        sudo mount -t proc /proc rootfs/proc
        sudo mount --rbind /dev rootfs/dev
        sudo mount --rbind /sys rootfs/sys
    - run: sudo chroot rootfs /bin/apt-get -y install python3 wget git live-build debian-archive-keyring gpg dosfstools genisoimage squashfs-tools xorriso grub-common grub-pc-bin grub-efi-amd64-bin nano
    - run: sudo chroot rootfs /bin/wget https://github.com/dpkg123/lb-config/raw/main/build.py
    - run: sudo chroot rootfs /bin/python3 /build.py
    - run: sudo du -h -s rootfs/ci/live*.iso
      continue-on-error: true
    - name: upload iso
      uses: actions/upload-artifact@v4
      if: github.event_name == 'workflow_dispatch'
      with:
        name: iso-debian
        path: rootfs/ci/live-image-amd64.hybrid.iso
        retention-days: 14
    - name: upload log
      uses: actions/upload-artifact@v4
      if: github.event_name == 'push'
      with:
        name: log
        path: rootfs/ci/build.log

