name: ci
on:
  pull_request:
  workflow_dispatch:
  push:
  
jobs:
  live-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

  #  - uses: rokibhasansagar/slimhub_actions@main
    - run: sudo apt-get update
    - run: sudo apt-get -y install debootstrap
    - run: sudo debootstrap --arch=amd64 sid rootfs
    - run: sudo chroot rootfs /bin/apt-get -y install python3 wget git live-build debian-archive-keyring gpg dosfstools genisoimage squashfs-tools xorriso grub-common grub-pc-bin grub-efi-amd64-bin nano
    - run: sudo chroot rootfs /bin/wget https://github.com/dpkg123/lb-config/raw/main/build.py
    - run: sudo chroot rootfs /bin/python3 /build.py
